### ISSUE TITLE
Changing calculator precision options causes crash

### ISSUE THREAD

**Issue by JordanL2** [JordanL2/ModularCalculator#75]
Have any answer displayed in the output panel, change precision options (number size or prec) to something small.

```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/gui/options/common.py", line 111, in onStateChanged
    self.interface.applyConfig()
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/gui/interface.py", line 213, in applyConfig
    self.display.refresh()
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/gui/display.py", line 58, in refresh
    questionWidget, answerWidget = self.renderAnswer(row, n)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/gui/display.py", line 70, in renderAnswer
    (answerHtml, fractionHtml) = self.htmlservice.createAnswerFractionHtml(row, self.config.main['display'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/services/htmlservice.py", line 92, in createAnswerFractionHtml
    answerHtml += self.createAnswerHtml(row, options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/services/htmlservice.py", line 130, in createAnswerHtml
    answerFormatted = self.formatNumber(answer, options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/modularcalculatorinterface/services/htmlservice.py", line 191, in formatNumber
    return answer.to_string(calculator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/modularcalculator/objects/number.py", line 73, in to_string
    val = "{0:f}".format(round(dec_num, NUMBER['decimal_places']))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by JordanL2** [comment]
Bug also occurs if you clear output, increase size/prec both to 500, then enter:
```
2^1428
```

**Comment by JordanL2** [comment]
Problem was caused by number of decimal places being equal to or larger than the total number size. Fixed.
